controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 10 # Hz
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:

  ros__parameters:
    joints:
      - base
      - base_arm1
      - arm1_arm2
      - arm2_forks

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
      #    allow_integration_in_goal_trajectories: true
