name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go install github.com/equinix-labs/otel-cli@latest
      - run: otel-cli exec --service my-service --name "Initial job"; echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
